version: 2
updates:
    # Cargo workspace dependencies
    - package-ecosystem: "cargo"
      directory: "/rust/"
      schedule:
        interval: "weekly"
      cooldown:
        default-days: 7

    # GitHub Actions versions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "weekly"
      cooldown:
        default-days: 7